[build]
  command = "npm run build"
  publish = "dist"  # This should be 'dist' for Vite projects
  functions = "server"

[functions]
  node_bundler = "esbuild"

# Scheduled function that runs every minute
[[functions]]
  schedule = "* * * * *"
  path = "/process-webhooks" 
